import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

import javax.swing.JOptionPane;

/** 
 * Program used to guess 4 digits numbers randomly generated by the computer.
 * This like a lottery game that predicts a 4 digit number as well as the correct permutation of the
 * number in 3 trials.
 */
	
/**
 * 	DOSUNMU I. A.  7th December, 2018	1700hrs
 */
public class GuessingGame {

	// The  main method
	public static void main(String[] args) {
		JOptionPane.showMessageDialog(null, "Welcome to the Guessing Game!");
	
	int z = 3;
	boolean tryAgain = true;

	while (tryAgain == true) {
		int maxTrial = z;
		ArrayList<Integer> guess = new ArrayList<>();  
		ArrayList<Integer> random =  numberGenerator();
		while (maxTrial > 0) { 
			guess = guessedNumber();
			int indexMatch = 0;
			int match = 0;
			for (int i = 0; i<guess.size(); i++) {
			// Condition to check if the permutation or index matches of the random or winning number
				if (random.get(i).intValue() == guess.get(i).intValue()) {
					indexMatch++;
				}
				// Condition to check if a number is the 4 digit winning or random number generated
				if (random.contains(guess.get(i).intValue())) {
					match++;
				}
	
			}
		if (indexMatch == 4) {
			System.out.println("Congratulation! you have guessed the number correctly");
		}
		
		else  if (indexMatch < 4 ){
			maxTrial--;
			if (maxTrial > 1) {
				System.out.println("You have "+indexMatch+ " index match \nYou have " +match+ 
						" match(es)\nYou have " +maxTrial+ " attempts remaining");
				
			}
			else if (maxTrial == 1){
				System.out.println("You have "+indexMatch+ " index match \nYou have " +match+ 
						" match(es)\nThis is your last attempt");
				
			}
			else {
				System.out.println("Sorry you have failed to guess the number in " +z+ " attempts");
				System.out.println("Your index match is "+indexMatch+ " and match(es) is "+match); 
				System.out.print("The random number is: ");
				for (int k = 0; k < random.size(); k++) {
					System.out.print(random.get(k).intValue());
				}
				System.out.println("");
			} 
		}
		}
		System.out.println("");
		System.out.println("Do you want to try again? Enter 1 if yes or 0 to end game");
		Scanner sc = new Scanner(System.in);
		int flag = sc.nextInt();
		if(flag != 1) {
			tryAgain = false;
		}
	
	}
	} 
	// Method to take user input as string and parsed it to an array list of integers
	static ArrayList<Integer> guessedNumber() {
		Scanner input = new Scanner(System.in);
		ArrayList<Integer> number = new ArrayList<>(4);
		System.out.println("\nGuess 4 different digits (0-9): ");
		String yourNumber = input.nextLine();
		
		if (yourNumber.length() != 4){
			System.out.println("Enter a 4 digit integer");
			guessedNumber();	
		} 
		// 	Catching a Number format Exception
		try {
		 		for (int i = 0; i<4; i++) {
			number.add(Integer.parseInt(String.valueOf(yourNumber.charAt(i))));
		}
		} catch (Exception NumberFormatException) {
			System.out.println("You entered a character (i.e a+_-%  etc). Enter 4 digit integers only");
			guessedNumber();
		}

		return number;
	}

	// 	Method to generate random or winnning normal
	static ArrayList<Integer> numberGenerator () {
		ArrayList<Integer>  guess = new ArrayList<>(4); 
		Random rand = new Random();
		while(guess.size() < 4) {
		int	number = rand.nextInt(10);
			if (!guess.contains(number)) 
				guess.add(number);
		}
		
			return guess;
		}
		
}
