# CodeLagos project
import turtle
turtle.bgcolor("grey")
turtle.showturtle()
turtle.penup()
turtle.goto(0,150)
turtle.pendown()
turtle.fillcolor("purple")
turtle.pensize(40)
turtle.pencolor("white")
turtle.right(45)
turtle.color("yellow")
turtle.forward(180)
turtle.color("red")
turtle.circle(50)
turtle.right(90)
turtle.color("green")
turtle.forward(180)
turtle.color("blue")
turtle.circle(50)
turtle.right(450)
turtle.color("red")
turtle.forward(180)
turtle.color("yellow")
turtle.circle(50)
turtle.color("white")
turtle.write("\n\n\n\n                        WELCOME TO MY PJ! \n\n                     PLS CLICK ON CLOSE BTN")
turtle.right(90)
turtle.color("blue")
turtle.forward(180)
turtle.color("green")
turtle.circle(50)
turtle.done()
print("Hello World")
print("          ********************************************************       ")
print("          _____ Welcome to my Petrol Station Meter Calculator_____       ")
print("          ********************************************************       ")
print("Name: Alake Edah, Email: alakedah777@gmail.com, Center: Ikeja Old Secretariat Library, Batch 5, Dec. 2018 \n")
print("Which fuel will you like to buy? \na)Petrol\nb) Diesel \nc) Kero \n")
option = input("Choose an option:")
if option =="a":
    print("Enter your amount") 
    amount =int(input("Amount:"))
    litre = round(amount / 145,2)
    print (amount,"naira will get you",litre,"litres of Petrol" )
    
elif option =="b":
    print("Enter your amount")
    amount =int(input("Amount:"))
    litre = round(amount / 255,2)
    print ( amount,"naira will get you",litre,"litres of Diesel" )
    
elif option =="c":
    print("Enter your amount")
    amount = int(input("Amount:"))
    litre = round(amount / 260,2)
    print(amount,"naira will get you",litre,"litres of Kero")
    
else:
    print("Please choose an option")
print("THANK YOU FOR YOUR PATRONAGE")

