print ("         •*")
print ("        **•*")
print ("       ****•*")
print ("      ******•*")
print ("     ******•***          ***     ")
print ("    ******•*****        *   *    ")
print ("   ******•*******      *_____*   ")
print ("       *•*****           • •     ")
print ("      *•*******       _(L___j)   ")
print ("     ***•*******     l l     l l ")
print ("    *****•*******    l l     l l ")
print ("   *******•*******   l l_____l l ")
print ("  *********•******* ooo! _ _ !ooo")
print ("      ******•**        ! ! ! !   ")
print ("     ********•**      _! ! ! !_  ")
print ("    **********•**    (___! !___) ")
print ("   **********•****")
print ("  **********•******      _________ ")
print (" **********•********     l___l l__l")
print ("         l  l            l___l l__l")
print ("         l__l            l   l l  l")
print ("                         l___l_l__l")
print ("                                  ")
print ("M       M EEEE RR   RR   Y   Y")
print ("MM     MM E    R R  R R   Y Y")
print ("M M   M M EEE  RR   RR     Y")
print ("M  M M  M E    R R  R R    Y")
print ("M   M   M EEEE R  R R  R   Y")
print ("")
print ("        CHRISTMAS!!!!")
print ("")
print ("Note: Do you think we can reach 100 Likes?")
print ("")
print ("        *****")
print ("       * * * *    *")
print ("      * !___! *  *")
print ("       *************")
print (" #*****   *  *****#")
print ("     *    *   *")
print ("    *     *    *")
print ("    *          *")
print ("     **********")
