print("Name: UKPAI JOHN UCHECHUKWU")
print("Email: Ucjohn471@gmail.com")
print("Purpose: How to draw shapes")
print("Number: 08185613065")
print("\t\tBatch 5 Codelagos")
#import the turtle module
import turtle
#Write the code here
turtle.pendown()
turtle.penup()
turtle.setposition(-90,90)
turtle.pendown()
turtle.pensize(10)
turtle.color("red","green")
turtle.begin_fill()
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.end_fill()
turtle.penup()



turtle.pendown()
turtle.penup()
turtle.setposition(-200,200)
turtle.pendown()
turtle.pensize(10)
turtle.color("red","white")
turtle.begin_fill()
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.end_fill()
turtle.penup()

turtle.pendown()
turtle.penup()
turtle.setposition(-300,300)
turtle.pendown()
turtle.pensize(10)
turtle.color("red","green")
turtle.begin_fill()
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.end_fill()
turtle.penup()


turtle.home()
turtle.pensize(8)
turtle.pencolor("red")
turtle.color("red",)
turtle.begin_fill()
turtle.setposition(280,-280)
turtle.pendown()
turtle.circle(80)
turtle.penup()

turtle.home()
turtle.pensize(8)
turtle.pencolor("green")
turtle.setposition(320,-320)
turtle.pendown()
turtle.circle(130)
turtle.penup()

turtle.home()
turtle.pensize(8)
turtle.pencolor("blue")
turtle.setposition(400,-400)
turtle.pendown()
turtle.circle(220)
turtle.end_fill()
turtle.hideturtle()




#End the program loop
turtle.done()
